apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels: 
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.image }}:{{ .Values.tag }}
        volumeMounts:
        - name: config-path
          mountPath: /config
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
           secretKeyRef:
            name: root-password
            key: root-password
        - name: MYSQL_DATABASE
          value: "kodi"
        - name: MYSQL_USER
          value: "kodi"
        - name: MYSQL_PASSWORD
          valueFrom:
           secretKeyRef:
            name: kodi-password
            key: kodi-password
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: Europe/London
      volumes:
      - hostPath:
          path: {{ .Values.config_path }}
        name: config-path