apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels: 
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.image }}:{{ .Values.tag }}
        volumeMounts:
        - name: www
          mountPath: /var/www
        env:
        - name: password
          valueFrom:
           secretKeyRef:
            name: password
            key: password
      volumes:
      - hostPath:
          path: {{ .Values.www_path }}
        name: www