apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels: 
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.image }}:{{ .Values.tag }}
        volumeMounts:
        - name: config
          mountPath: /home/keybase/.config/arnie
        env:
        - name: KEYBASE_PAPERKEY
          valueFrom:
           secretKeyRef:
            name: arnie-key
            key: KEYBASE_PAPERKEY
        - name: KEYBASE_USERNAME
          value: arnie
      volumes:
      - hostPath:
          path: {{ .Values.config_path }}
        name: config
